### ISSUE TITLE
Larger text editing fields in edit experience

### ISSUE THREAD

**Issue by carolynbowes** [massgov/feature-requests#108] opened 2018-07-10 18:10 UTC
User story:
I need larger text editing boxes within the editing experience. (from 2 users)

Reference: https://jira.mass.gov/browse/DP-9044

**Comment by lmirabile** [comment] 2018-07-31 01:25
This is an exact duplicate of #51, so I'm closing it.

**Closed by lmirabile** 2018-07-31 01:25 UTC
Labels: AX Authoring Improvements, edit team
